databases:
  - name: travel-chatbot-db
    plan: free
    databaseName: travel_chatbot
    

services:
  - type: web
    name: travel-chatbot-app
    env: docker
    plan: free
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: travel-chatbot-db
          property: connectionString
      - key: JWT_SECRET
        sync: false
